src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EvenementsRepository::class)
 */
class Evenement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $title;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start;

    /**
     * @ORM\Column(type="datetime")
     */
    private $end;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $all_day;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAllDay(): ?bool
    {
        return $this->all_day;
    }

    public function setAllDay(bool $all_day): self
    {
        $this->all_day = $all_day;

        return $this;
    }
}

src/Controller/AdministratorController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin")
 */
class AdministratorController extends AbstractController
{
    /**
     * @Route("/", name="administrator-dashboard")
     */
    public function indexDashboard(): Response
    {
        return $this->render('administrator/dashboard.html.twig');
    }
}

src/Controller/CalendarController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EvenementsType;
use App\Service\AlertServiceInterface;
use App\Repository\EvenementsRepository;
use Symfony\Contracts\Cache\CacheInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/admin/calendar")
 */
class CalendarController extends AbstractController
{
    /**
     * @Route("/", name="calendar_index", methods={"GET"})
     */
    public function index(
        EvenementsRepository $EvenementsRepository): Response {
       

        return $this->render('administrator/calendar/calendar_index.html.twig', [            
            'evenements' => $EvenementsRepository->findAll()
        ]);
    }

    /**
     * @Route("/nouvel-evenement", name="calendar_new", methods={"GET","POST"})
     */
    public function new(Request $request,AlertServiceInterface $alertService): Response
    {
        $evenement = new Evenement();
        $form = $this->createForm(EvenementsType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($evenement);
            $entityManager->flush();
            // $alertService->success('Vous avez ajouté un nouvel évènement');
           

            return $this->redirectToRoute('calendar_index');
        }

        return $this->render('administrator/calendar/new_calendar.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="calendar_show", methods={"GET"})
     */
    public function show(Evenement $evenement): Response
    {
        return $this->render('administrator/calendar/show_calendar.html.twig', [
            'evenement' => $evenement,
        ]);
    }

    /**
     * @Route("/{id}/edition", name="calendar_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Evenement $evenement): Response
    {
        $form = $this->createForm(EvenementsType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('calendar_index');
        }

        return $this->render('administrator/calendar/edit_calendar.html.twig', [
            'evenement' => $evenement,
            'form' => $form
        ]);
    }

    /**
     * @Route("/{id}", name="calendar_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Evenement $evenement): Response
    {
        if ($this->isCsrfTokenValid('delete' . $evenement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($evenement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('calendar_index');
    }
}

templates/Administrator/calendar/calendar_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">Sauvegarder</button>
{{ form_end(form) }}

templates/Administrator/calendar/calendar_index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil-Calendrier{% endblock %}

{% block body %}
<header id="hero">
    <h1>Accueil-Calendrier</h1>
</header>
<main class="container">
    <ol class="breadcrumbs">
        <li>
            <a href="{{path('administrator-dashboard')}}">Accueil tableau de bord</a>
        </li>
        <li>Article-Calendrier</li>
    </ol>
    <a href="{{ path('calendar_new')}}" class="btn btn-light utilisateur">Nouvel Evenement</a>
    <table class="table table-utilisateurs" data-toggle="table" data-pagination="true" data-page-size="5">
        <thead>
            <tr>
                <th>Titre</th>
                <th>Début</th>
                <th>Fin</th>
                <th>Description</th>
                <th>Toute la journée</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
            {% for evenement in evenements %}

                <tr>
                    <td data-label="Titre">{{ evenement.title }}</td>
                    <td data-label="Date début">{{ evenement.start ? evenement.start|date('Y-m-d H:i:s') : '' }}</td>
                    <td data-label="Date fin">{{ evenement.end ? evenement.end|date('Y-m-d H:i:s') : '' }}</td>
                    <td data-label="Description">{{ evenement.description }}</td>
                    <td data-label="Journée">{{ evenement.allDay ? 'Yes' : 'No' }}</td>
                    <td data-label="Actions" class="action">
                        <button onclick="window.location.href='{{ path('calendar_show', {'id': evenement.id}) }}';" type="button" class="btn btn-success" title="show-article">test</button>
                        <button onclick="window.location.href='{{ path('calendar_edit', {'id': evenement.id}) }}';" type="button" class="btn btn-success" title="show-article">Edit</button>
                        {{ include('administrator/calendar/delete_form_calendar.html.twig') }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="10">Pas d'évenement trouvé</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{% endblock %}

templates/Administrator/calendar/delete_form_calendar.html.twig
<form method="post" action="{{ path('calendar_delete', {'id': evenement.id}) }}" onsubmit="return confirm('Êtes-vous sûr de bien vouloir supprimer cet élément?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ evenement.id) }}">
    <button class="btn btn-danger"><i class="far fa-trash-alt"></i></button>   
</form>

templates/Administrator/calendar/edit_calendar.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition Calendrier{% endblock %}

{% block body %}
<header id="hero">
	<h1>Edition-Calendrier</h1>
</header>
<main class="container">
    <ol class="breadcrumbs">
        <li>
            <a href="{{path('administrator-dashboard')}}">Accueil tableau de bord</a>
        </li>
        <li>
            <a href="{{path('calendar_index')}}">Gestion calendrier</a>
        </li>
        <li>Calendrier Edition</li>
    </ol>
    <a href="{{ path('calendar_index')}}" class="btn btn-primary">Retour à la liste</a>
    <div class="btn-2">
    {{ include('administrator/calendar/calendar_form.html.twig', {'button_label': 'Mise à jour'}) }}
    {{ include('administrator/calendar/delete_form_calendar.html.twig') }}
</main>
{% endblock %}

templates/Administrator/calendar/new_calendar.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel Evènement{% endblock %}

{% block body %}
<header id="hero">
	<h1>Nouvel-Evènement</h1>
</header>
<main class="container">
    <ol class="breadcrumbs">
        <li>
            <a href="{{path('administrator-dashboard')}}">Accueil tableau de bord</a>
        </li>
        <li>
            <a href="{{path('calendar_index')}}">Gestion calendrier</a>
        </li>
        <li>Calendrier-Ajout Evenement</li>
    </ol>
    <a href="{{ path('calendar_index')}}" class="btn btn-primary">Retour à la liste</a>
    {{ include('administrator/calendar/calendar_form.html.twig') }}
</main>
{% endblock %}

templates/Administrator/calendar/show_calendar.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aperçu Calendrier{% endblock %}

{% block body %}
<header id="hero">
    <h1>Aperçu Calendrier</h1>
</header>
<main class="container">
    <ol class="breadcrumbs">
        <li>
            <a href="{{path('administrator-dashboard')}}">Accueil tableau de bord</a>
        </li>
        <li>
            <a href="{{path('calendar_index')}}">Gestion calendrier</a>
        </li>
        <li>Calendrier-Aperçu Evenement</li>
    </ol>
    <a href="{{ path('calendar_index')}}" class="btn btn-primary">Retour à la liste</a>
    <table class="table">
        <tbody>
            <tr>
                <th>Titre</th>
                <td>{{ evenement.title }}</td>
            </tr>
            <tr>
                <th>Date Début</th>
                <td>{{ evenement.start ? evenement.start|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date fin</th>
                <td>{{ evenement.end ? evenement.end|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ evenement.description }}</td>
            </tr>
            <tr>
                <th>Toute la journée</th>
                <td>{{ evenement.allDay ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>
    <a href="{{ path('calendar_edit', {'id': evenement.id}) }}">édition</a>
    {{ include('administrator/calendar/delete_form_calendar.html.twig') }}
</main>
{% endblock %}