src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 * @Vich\Uploadable
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="string", length=10000)
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     */
    private $Date_de_publication;

    /**
     * @ORM\ManyToMany(targetEntity=CategorieArticle::class, inversedBy="articles")
     */
    private $Categories;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imagesArticle;

     /**
     * @Vich\UploadableField(mapping="imagesArticle", fileNameProperty="imagesArticle")
     * @var File
     */
    private $imageFile;

    public function __construct()
    {
        $this->Categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateDePublication(): ?\DateTimeInterface
    {
        return $this->Date_de_publication;
    }

    public function setDateDePublication(\DateTimeInterface $Date_de_publication): self
    {
        $this->Date_de_publication = $Date_de_publication;

        return $this;
    }

    /**
     * @return Collection|CategorieArticle[]
     */
    public function getCategories(): Collection
    {
        return $this->Categories;
    }

    public function addCategory(CategorieArticle $category): self
    {
        if (!$this->Categories->contains($category)) {
            $this->Categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(CategorieArticle $category): self
    {
        $this->Categories->removeElement($category);

        return $this;
    }

    public function getImagesArticle(): ?string
    {
        return $this->imagesArticle;
    }

    public function setImagesArticle(?string $imagesArticle): self
    {
        $this->imagesArticle = $imagesArticle;

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        if ($image) {
            $this->updated_at = new \DateTime('now');
        }
    }
    public function getImageFile()
    {
        return $this->imageFile;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Titre', TextType::class)
            ->add('description', CKEditorType::class)
            ->add('Date_de_publication', DateTimeType::class, [
                'date_label' => 'Date de publication'
            ])
            ->add('imageFile', VichImageType::class, [
                'required' => false,
                'download_link' => false,
                'image_uri' => false
                ])
            ->add('Categories')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/AdministratorController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin")
 */
class AdministratorController extends AbstractController
{
    /**
     * @Route("/", name="administrator-dashboard")
     */
    public function indexDashboard(): Response
    {
        return $this->render('administrator/dashboard.html.twig');
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use App\Service\AlertServiceInterface;
use Symfony\Contracts\Cache\CacheInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/admin/article")
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="article_index", methods={"GET"})
     */
    public function indexArticle(ArticleRepository $articleRepository): Response {
      

        return $this->render('administrator/article/article_index.html.twig', [           
            'articles'=>$articleRepository->findAll()
        ]);
    }

    /**
     * @Route("/nouvelle_article", name="article_new", methods={"GET","POST"})
     */
    public function newArticle(Request $request,AlertServiceInterface $alertService): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();
            $alertService->success('Vous avez ajouté un nouvel article');     
           
            return $this->redirectToRoute('article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('administrator/article/new_article.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_show", methods={"GET"})
     */
    public function showArticle(Article $article): Response
    {
        return $this->render('administrator/article/show_article.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{id}/edition", name="article_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Article $article): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('administrator/article/edit_article.html.twig', [
            'article' => $article,
            'form' => $form
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", methods={"POST"})
     */
    public function deleteArticle(Request $request, Article $article): Response
    {
        if ($this->isCsrfTokenValid('delete' . $article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('article_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/Administrator/article/article_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">Sauvegarder</button>
{{ form_end(form) }}

templates/Administrator/article/article_index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil-article gestion {% endblock %}

{% block body %}
<header id="hero">
    <h1>Accueil-articles gestion</h1>
</header>
<main class="container">
    <ol class="breadcrumbs">
        <li>
            <a href="{{path('administrator-dashboard')}}">Accueil tableau de bord</a>
        </li>
        <li>Article Gestion</li>
    </ol>
    <a href="{{ path('article_new')}}" class="btn btn-light utilisateur">Nouvel article</a>
        <table class="table table-utilisateurs" data-toggle="table" data-pagination="true" data-page-size="5">
            <thead>
                <tr>
                    <th>Titre</th>
                    <th>Description</th>
                    <th>Date de publication</th>
                    <th>Article Images</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for article in articles %}
                    <tr>
                        <td data-label="Titre">{{ article.Titre }}</td>
                        <td data-label="description">{{ article.description|raw }}</td>
                        <td data-label="Date Publication">{{ article.DateDePublication ? article.DateDePublication|date('Y-m-d') : '' }}</td>
                        <td data-label="Images Article"><img class="thumbnail-article" src="{{vich_uploader_asset(article,'imageFile') }}" alt="{{article.titre}}"/></td>                        
                        <td data-label="Actions" class="action">
                            <a href="{{ path('article_show', {'id': article.id}) }}" class="btn btn-success"><i class="fas fa-eye"></i></a>
                            <a href="{{ path('article_edit', {'id': article.id}) }}" class="btn btn-success"><i class="fas fa-edit"></i></a>
                            {{ include('administrator/article/delete_form_article.html.twig') }}
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="6">Pas d'article trouvé</td>
                    </tr>
                {% endfor %}
            </tbody>
    </table>
</main>
{% endblock %}

templates/Administrator/article/delete_form_article.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Etes-vous sur de vouloir supprimer');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn btn-danger">	<i class="far fa-trash-alt"></i></button>   
</form>

templates/Administrator/article/edit_article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article Edition{% endblock %}

{% block body %}
<header id="hero">
    <h1>Article Edition</h1>
</header>
<main class="container">
    <ol class="breadcrumbs">
        <li>
            <a href="{{path('administrator-dashboard')}}">Accueil tableau de bord</a>
        </li>
        <li>
            <a href="{{path('article_index')}}">Gestion Article</a>
        </li>
        <li>Article Edition</li>
    </ol>
    <a href="{{ path('article_index')}}" class="btn btn-primary">Retour à la liste</a>
    {{ include('administrator/article/article_form.html.twig', {'button_label': 'Mise à jour'}) }}
    {{ include('administrator/article/delete_form_article.html.twig') }}
</main>
{% endblock %}

templates/Administrator/article/new_article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel Article{% endblock %}

{% block body %}
<header id="hero">
    <h1>Nouvel article</h1>
</header>
<main class="container">
    <ol class="breadcrumbs">
        <li>
            <a href="{{path('administrator-dashboard')}}">Accueil tableau de bord</a>
        </li>
        <li>
            <a href="{{path('article_index')}}">Gestion Article</a>
        </li>
        <li>Nouvel Article</li>
    </ol>
    <a href="{{ path('article_index')}}" class="btn btn-primary">Retour à la liste</a>
    {{ include('administrator/article/article_form.html.twig') }}
</main>
{% endblock %}

templates/Administrator/article/show_article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aperçu Article{% endblock %}

{% block body %}
<header id="hero">
    <h1>Aperçu d'un article</h1>
</header>
<main class="container">
    <ol class="breadcrumbs">
        <li>
            <a href="{{path('administrator-dashboard')}}">Accueil tableau de bord</a>
        </li>
        <li>
            <a href="{{path('article_index')}}">Gestion Article</a>
        </li>
        <li>Aperçu Article</li>
    </ol>
    <a href="{{ path('article_index')}}" class="btn btn-primary">Retour à la liste</a>
    <table class="table">
        <tbody>
            <tr>
                <th>Titre</th>
                <td>{{ article.Titre }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ article.description }}</td>
            </tr>
            <tr>
                <th>Date de publication</th>
                <td>{{ article.DateDePublication ? article.DateDePublication|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Image Article</th>
                <td>{{ article.imagesArticle }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('article_edit', {'id': article.id}) }}">edition</a>

    {{ include('administrator/article/delete_form_article.html.twig') }}
</main>
{% endblock %}